// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0
// source: pb/rainbowmist.proto

package rainbowmist

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BaseAsset  string `protobuf:"bytes,1,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	QuoteAsset string `protobuf:"bytes,2,opt,name=quote_asset,json=quoteAsset,proto3" json:"quote_asset,omitempty"`
	Decimals   string `protobuf:"bytes,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
}

func (x *GetPriceRequest) Reset() {
	*x = GetPriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rainbowmist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceRequest) ProtoMessage() {}

func (x *GetPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rainbowmist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceRequest.ProtoReflect.Descriptor instead.
func (*GetPriceRequest) Descriptor() ([]byte, []int) {
	return file_pb_rainbowmist_proto_rawDescGZIP(), []int{0}
}

func (x *GetPriceRequest) GetBaseAsset() string {
	if x != nil {
		return x.BaseAsset
	}
	return ""
}

func (x *GetPriceRequest) GetQuoteAsset() string {
	if x != nil {
		return x.QuoteAsset
	}
	return ""
}

func (x *GetPriceRequest) GetDecimals() string {
	if x != nil {
		return x.Decimals
	}
	return ""
}

type GetUSDPriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Asset    string `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Decimals string `protobuf:"bytes,2,opt,name=decimals,proto3" json:"decimals,omitempty"`
}

func (x *GetUSDPriceRequest) Reset() {
	*x = GetUSDPriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rainbowmist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUSDPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUSDPriceRequest) ProtoMessage() {}

func (x *GetUSDPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rainbowmist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUSDPriceRequest.ProtoReflect.Descriptor instead.
func (*GetUSDPriceRequest) Descriptor() ([]byte, []int) {
	return file_pb_rainbowmist_proto_rawDescGZIP(), []int{1}
}

func (x *GetUSDPriceRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

func (x *GetUSDPriceRequest) GetDecimals() string {
	if x != nil {
		return x.Decimals
	}
	return ""
}

type GetPriceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Price  string `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	Status bool   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *GetPriceReply) Reset() {
	*x = GetPriceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_rainbowmist_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPriceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPriceReply) ProtoMessage() {}

func (x *GetPriceReply) ProtoReflect() protoreflect.Message {
	mi := &file_pb_rainbowmist_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPriceReply.ProtoReflect.Descriptor instead.
func (*GetPriceReply) Descriptor() ([]byte, []int) {
	return file_pb_rainbowmist_proto_rawDescGZIP(), []int{2}
}

func (x *GetPriceReply) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetPriceReply) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_pb_rainbowmist_proto protoreflect.FileDescriptor

var file_pb_rainbowmist_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x62, 0x2f, 0x72, 0x61, 0x69, 0x6e, 0x62, 0x6f, 0x77, 0x6d, 0x69, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x61, 0x69, 0x6e, 0x62, 0x6f, 0x77, 0x6d,
	0x69, 0x73, 0x74, 0x22, 0x6d, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x61, 0x73, 0x65,
	0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x5f, 0x61,
	0x73, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x71, 0x75, 0x6f, 0x74,
	0x65, 0x41, 0x73, 0x73, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61,
	0x6c, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61,
	0x6c, 0x73, 0x22, 0x46, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x53, 0x44, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x73, 0x73, 0x65, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x22, 0x3d, 0x0a, 0x0d, 0x47, 0x65,
	0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0xa3, 0x01, 0x0a, 0x0b, 0x52, 0x61,
	0x69, 0x6e, 0x62, 0x6f, 0x77, 0x6d, 0x69, 0x73, 0x74, 0x12, 0x46, 0x0a, 0x08, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1c, 0x2e, 0x72, 0x61, 0x69, 0x6e, 0x62, 0x6f, 0x77, 0x6d,
	0x69, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x61, 0x69, 0x6e, 0x62, 0x6f, 0x77, 0x6d, 0x69, 0x73,
	0x74, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x4c, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x53, 0x44, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x1f, 0x2e, 0x72, 0x61, 0x69, 0x6e, 0x62, 0x6f, 0x77, 0x6d, 0x69, 0x73, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x53, 0x44, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x72, 0x61, 0x69, 0x6e, 0x62, 0x6f, 0x77, 0x6d, 0x69, 0x73, 0x74, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42,
	0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x72, 0x61, 0x69, 0x6e, 0x62, 0x6f, 0x77, 0x6d, 0x69, 0x73, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_rainbowmist_proto_rawDescOnce sync.Once
	file_pb_rainbowmist_proto_rawDescData = file_pb_rainbowmist_proto_rawDesc
)

func file_pb_rainbowmist_proto_rawDescGZIP() []byte {
	file_pb_rainbowmist_proto_rawDescOnce.Do(func() {
		file_pb_rainbowmist_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_rainbowmist_proto_rawDescData)
	})
	return file_pb_rainbowmist_proto_rawDescData
}

var file_pb_rainbowmist_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_rainbowmist_proto_goTypes = []interface{}{
	(*GetPriceRequest)(nil),    // 0: rainbowmist.GetPriceRequest
	(*GetUSDPriceRequest)(nil), // 1: rainbowmist.GetUSDPriceRequest
	(*GetPriceReply)(nil),      // 2: rainbowmist.GetPriceReply
}
var file_pb_rainbowmist_proto_depIdxs = []int32{
	0, // 0: rainbowmist.Rainbowmist.GetPrice:input_type -> rainbowmist.GetPriceRequest
	1, // 1: rainbowmist.Rainbowmist.GetUSDPrice:input_type -> rainbowmist.GetUSDPriceRequest
	2, // 2: rainbowmist.Rainbowmist.GetPrice:output_type -> rainbowmist.GetPriceReply
	2, // 3: rainbowmist.Rainbowmist.GetUSDPrice:output_type -> rainbowmist.GetPriceReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_rainbowmist_proto_init() }
func file_pb_rainbowmist_proto_init() {
	if File_pb_rainbowmist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_rainbowmist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rainbowmist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUSDPriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_rainbowmist_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPriceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_rainbowmist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_rainbowmist_proto_goTypes,
		DependencyIndexes: file_pb_rainbowmist_proto_depIdxs,
		MessageInfos:      file_pb_rainbowmist_proto_msgTypes,
	}.Build()
	File_pb_rainbowmist_proto = out.File
	file_pb_rainbowmist_proto_rawDesc = nil
	file_pb_rainbowmist_proto_goTypes = nil
	file_pb_rainbowmist_proto_depIdxs = nil
}
